import { analyzeRepository } from "./ai";
import { getRepoContents, getRepoReadme } from "./github";

// check Dockerfile
async function checkDockerfile(token: string, owner: string, repo: string) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/Dockerfile`, {
    headers: { Authorization: `Bearer ${token}` }
  });
  return res.status === 200;
}

// get default branch
async function getDefaultBranch(token: string, owner: string, repo: string) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
    headers: { Authorization: `Bearer ${token}` }
  });
  const data = await res.json();
  return data.default_branch;
}

// get branch latest commit sha
async function getBranchSha(token: string, owner: string, repo: string, branch: string) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    headers: { Authorization: `Bearer ${token}` }
  });
  const data = await res.json();
  return data.object.sha;
}

// create new branch
async function createBranch(token: string, owner: string, repo: string, branchName: string, sha: string) {
  await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      ref: `refs/heads/${branchName}`,
      sha
    })
  });
}

// create/update file
async function createOrUpdateFile(token: string, owner: string, repo: string, path: string, content: string, branch: string, message: string) {
  await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      message,
      content: Buffer.from(content).toString("base64"),
      branch
    })
  });
}

// create PR
async function createPR(token: string, owner: string, repo: string, branchName: string, baseBranch: string) {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      title: "automatically generate Dockerfile and workflow(AICD)",
      head: branchName,
      base: baseBranch,
      body: "This PR is automatically generated by AICD and includes Dockerfile and GitHub Actions workflow."
    })
  });
  const data = await res.json();
  return data.html_url;
}

// generate Dockerfile content
function buildDockerfile(result: {
  baseImage: string;
  installCmd: string;
  startCmd: string;
  ports: number[];
}) {
  return `FROM ${result.baseImage}
WORKDIR /app
COPY . .
RUN ${result.installCmd}
EXPOSE ${result.ports.join(" ")}
CMD ${JSON.stringify(result.startCmd.split(" "))}
`;
}

// generate GitHub Actions workflow content
function buildWorkflow() { 
  return `name: Build and Push Docker Image
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker.yml'
      - '**/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/\${{ github.repository_owner }}/\${{ github.event.repository.name }}:latest .
      - name: Push Docker image
        run: |
          docker push ghcr.io/\${{ github.repository_owner }}/\${{ github.event.repository.name }}:latest
`;
}

// main AI analysis and automatic completion of Dockerfile and workflow
export async function autoAnalyzeAndPush(
  token: string,
  userId: string,
  owner: string,
  repo: string
): Promise<{ message?: string; prUrl?: string }> {
  // check Dockerfile
  const hasDockerfile = await checkDockerfile(token, owner, repo);
  if (hasDockerfile) return { message: "Dockerfile already exists." };

  // get repo contents and readme
  const contents = await getRepoContents(userId, owner, repo);
  const readme = await getRepoReadme(userId, owner, repo);
  const signal = {
    files: contents.map(item => item.name),
    readme: readme?.slice(0, 4000)
  };
  // AI analysis
  const { result } = await analyzeRepository(signal);
  // generate Dockerfile and workflow content
  const dockerfileContent = buildDockerfile(result);
  const workflowContent = buildWorkflow();
  // 5. gain branch and sha
  const baseBranch = await getDefaultBranch(token, owner, repo);
  const sha = await getBranchSha(token, owner, repo, baseBranch);
  // 6. create new branch
  const branchName = `aicd-dockerfile-${Date.now()}`;
  await createBranch(token, owner, repo, branchName, sha);
  // 7. upload Dockerfile and workflow
  await createOrUpdateFile(token, owner, repo, 'Dockerfile', dockerfileContent, branchName, 'add Dockerfile by AI');
  await createOrUpdateFile(token, owner, repo, '.github/workflows/docker.yml', workflowContent, branchName, 'add workflow for Docker image build and push');
  // 8. create PR
  const prUrl = await createPR(token, owner, repo, branchName, baseBranch);
  return { prUrl };
}